export const PERMISSION_DESCRIPTIONS: Readonly<Record<string, string>> = {
  'app.admin_config.view': 'View the global Admin Configuration panel.',
  'app.admin_config.edit': 'Edit global Admin Configuration settings.',
  'app.admin_config.external_mysql.test': 'Test external MySQL connectivity/verification settings.',
  'app.branding.assets.upload': 'Upload branding assets (logo, favicon, etc.).',
  'app.branding.assets.delete': 'Delete branding assets.',
  'app.fonts.upload': 'Upload custom fonts.',
  'app.fonts.delete': 'Delete custom fonts.',
  'app.users.unlock': 'Unlock locked user accounts.',
  'app.users.placeholder.list': 'List placeholder users created by imports.',
  'app.users.placeholder.convert': 'Convert a placeholder user into a regular user.',
  'app.users.placeholder.merge': 'Merge a placeholder user into an existing user.',
  'app.roles.list': 'List roles (built-in + custom).',
  'app.roles.create': 'Create a custom role.',
  'app.roles.update': 'Edit a custom role’s permissions.',
  'app.roles.delete': 'Delete a custom role.',
  'app.roles.assign_app_admin': 'Grant or revoke App Admin to a user.',
  'app.permission_sets.list': 'List permission sets.',
  'app.permission_sets.create': 'Create a permission set.',
  'app.permission_sets.update': 'Edit a permission set.',
  'app.permission_sets.delete': 'Delete a permission set.',
  'users.me.view': 'View your own user profile.',
  'users.me.update': 'Update your own profile.',
  'users.me.avatar.upload': 'Upload your profile picture.',
  'users.me.avatar.delete': 'Delete your profile picture.',
  'users.me.preferences.view': 'View your preferences.',
  'users.me.preferences.update': 'Update your preferences.',
  'workspaces.list': 'List workspaces you can access.',
  'workspaces.view': 'View a workspace.',
  'workspaces.update': 'Update workspace settings.',
  'workspaces.delete': 'Delete a workspace.',
  'workspaces.members.view': 'View workspace members.',
  'workspaces.members.add': 'Add a member to a workspace.',
  'workspaces.members.remove': 'Remove a member from a workspace.',
  'workspaces.members.role.update': 'Change a workspace member’s role.',
  'boards.create': 'Create a board.',
  'boards.list': 'List boards you can access.',
  'boards.view': 'View a board.',
  'boards.update': 'Update board settings/content.',
  'boards.delete': 'Delete a board.',
  'boards.reorder_in_home': 'Reorder boards on the home page.',
  'boards.settings.open': 'Open Board Settings (UI affordance).',
  'boards.settings.update': 'Update board settings (appearance + behavior).',
  'boards.themes.changetheme': 'Open Theme & Background tab and apply board theme/background changes.',
  'boards.themes.customtheme': 'Create, edit, duplicate, and delete custom board themes.',
  'boards.members.view': 'View board members.',
  'boards.members.add': 'Add a member to a board.',
  'boards.members.remove': 'Remove a member from a board.',
  'boards.members.role.update': 'Change a board member’s role.',
  'boards.members.role.update.same':
    'Can update other board members role who have the same role hierarchy number as themself.',
  'boards.members.role.update.lower':
    'Can update other board members role to roles with a lower permissions hierarchy number than their own.',
  'boards.members.role.update.higher':
    'Can update other boards members role to roles with a higher permissions hierarchy number than their own.',
  'boards.members.role.update.samehigher':
    'Can update other boards members role to roles with the same number or higher.',
  'boards.members.role.update.samelower':
    'Can update other boards members role to roles with the same number or lower.',
  'boards.members.role.update.any':
    'Can update any board member role, including own role, to any role regardless of hierarchy.',
  'lists.create': 'Create a column (list).',
  'lists.list': 'List columns (lists) in a board.',
  'lists.view': 'View a column (list).',
  'lists.update': 'Update a column (list).',
  'lists.delete': 'Delete a column (list).',
  'lists.reorder': 'Reorder columns (lists).',
  'cards.create': 'Create a card.',
  'cards.list': 'List cards.',
  'cards.view': 'View a card.',
  'cards.update': 'Update a card.',
  'cards.dates.start.edit': 'Edit a card’s start date.',
  'cards.dates.due.edit': 'Edit a card’s due date.',
  'cards.dates.end.edit': 'Edit a card’s end date.',
  'cards.delete': 'Delete a card.',
  'cards.move': 'Move a card between columns.',
  'cards.reorder': 'Reorder cards within a column.',
  'cards.duplicate': 'Duplicate a card.',
  'cards.assignees.add': 'Assign users to a card.',
  'cards.assignees.remove': 'Remove assignees from a card.',
  'cards.reminders.create': 'Create reminders on a card.',
  'cards.reminders.update': 'Update reminders on a card.',
  'cards.reminders.delete': 'Delete reminders on a card.',
  'cards.reminders.dismiss': 'Dismiss a reminder.',
  'labels.view': 'View labels available on a board.',
  'labels.create': 'Create a label.',
  'labels.update': 'Update a label.',
  'labels.delete': 'Delete a label.',
  'labels.assign': 'Assign a label to a card.',
  'labels.remove': 'Remove a label from a card.',
  'attachments.upload': 'Upload an attachment to a card.',
  'attachments.delete': 'Delete an attachment from a card.',
  'comments.create': 'Create a comment.',
  'comments.update': 'Edit a comment (typically author-only).',
  'comments.delete': 'Delete a comment (typically author-only, with admin override where applicable).',
  'checklists.create': 'Create a checklist.',
  'checklists.update': 'Update a checklist.',
  'checklists.delete': 'Delete a checklist.',
  'checklists.items.create': 'Create a checklist item.',
  'checklists.items.update': 'Update a checklist item.',
  'checklists.items.delete': 'Delete a checklist item.',
  'invites.create': 'Create an invite link.',
  'invites.view': 'View invite links.',
  'invites.delete': 'Delete/revoke an invite link.',
  'invites.accept': 'Accept an invite link.',
  'import.trello': 'Start a Trello import.',
  'import.wekan': 'Start a Wekan import.',
  'export.board.json': 'Export a board as JSON.',
  'export.board.csv': 'Export a board as CSV.',
  'ui.admin_settings.open': 'Show the Admin Settings entry in the user menu.',
};

export const MEMBERS_ROLE_UPDATE_MODE_OPTIONS: ReadonlyArray<{ value: string; label: string }> = [
  { value: 'boards.members.role.update.same', label: 'Same hierarchy only' },
  { value: 'boards.members.role.update.lower', label: 'Lower hierarchy only' },
  { value: 'boards.members.role.update.higher', label: 'Higher hierarchy only' },
  { value: 'boards.members.role.update.samehigher', label: 'Same or higher hierarchy' },
  { value: 'boards.members.role.update.samelower', label: 'Same or lower hierarchy' },
  { value: 'boards.members.role.update.any', label: 'Any hierarchy (includes own role)' },
] as const;

export const MEMBERS_ROLE_UPDATE_MODE_KEYS = new Set(
  MEMBERS_ROLE_UPDATE_MODE_OPTIONS.map((option) => option.value),
);
