import type { BoardThemeDefinition } from './boardTheme.js';
import { BOARD_SCROLLBAR_TRACK_TRANSPARENT_HEXA } from './boardTheme.js';

/** System theme slugs that keep light navbar foreground despite smart-contrast rules. */
export const BOARD_NAVBAR_LIGHT_FG_THEME_SLUGS: readonly string[] = ['sunset-orange', 'mint-green', 'teal'];

/** Canonical built-in board themes — seeded into MongoDB `themes` on deploy. */
export const SYSTEM_BOARD_THEME_SEEDS: readonly BoardThemeDefinition[] = [
  {
    id: 'ocean-blue',
    name: 'Ocean Blue',
    palette: {
      navbarBg: '#1a5b99',
      navbarBorder: '#ffffff1f',
      canvasBg: '#2b82c9',
      listBg: '#ffffff',
      listHeaderText: '#172b4d',
      listMuted: '#5e6c84',
      listMutedStrong: '#42526e',
      listControlHoverBg: '#0000000f',
      listShadow: '0 1px 3px #0000001f',
      addListBg: '#ffffff33',
      addListBgHover: '#ffffff47',
      cardDetailBg: '#f8f9fb',
      cardDetailTitleText: '#1a1b1e',
      cardDetailText: '#868e96',
      cardDetailButtonBg: '#f0f1f4',
      cardDetailButtonText: '#1f2937',
      cardDetailButtonHoverBg: '#e4e6ea',
      cardDetailButtonHoverText: '#1f2937',
      scrollbarColor: 'unset',
      scrollbarTrackColor: BOARD_SCROLLBAR_TRACK_TRANSPARENT_HEXA,
    },
  },
  {
    id: 'sunset-orange',
    name: 'Sunset Orange',
    palette: {
      navbarBg: '#be7b12',
      navbarBorder: '#ffffff2e',
      canvasBg: '#d8902b',
      listBg: '#ffffff',
      listHeaderText: '#3b2b12',
      listMuted: '#6c5a40',
      listMutedStrong: '#503d27',
      listControlHoverBg: '#00000012',
      listShadow: '0 1px 3px #00000021',
      addListBg: '#ffffff33',
      addListBgHover: '#ffffff4d',
      cardDetailBg: '#fcfaf7',
      cardDetailTitleText: '#1a1b1e',
      cardDetailText: '#866a45',
      cardDetailButtonBg: '#f4efe8',
      cardDetailButtonText: '#3f2c19',
      cardDetailButtonHoverBg: '#eadfce',
      cardDetailButtonHoverText: '#3f2c19',
      scrollbarColor: 'unset',
      scrollbarTrackColor: BOARD_SCROLLBAR_TRACK_TRANSPARENT_HEXA,
    },
  },
  {
    id: 'forest-green',
    name: 'Forest Green',
    palette: {
      navbarBg: '#3f7d24',
      navbarBorder: '#ffffff29',
      canvasBg: '#5fa237',
      listBg: '#ffffff',
      listHeaderText: '#193018',
      listMuted: '#52684f',
      listMutedStrong: '#395139',
      listControlHoverBg: '#0000000f',
      listShadow: '0 1px 3px #0000001f',
      addListBg: '#ffffff33',
      addListBgHover: '#ffffff4d',
      cardDetailBg: '#f7faf7',
      cardDetailTitleText: '#1a1b1e',
      cardDetailText: '#56725a',
      cardDetailButtonBg: '#edf3ed',
      cardDetailButtonText: '#1e3221',
      cardDetailButtonHoverBg: '#dde7dd',
      cardDetailButtonHoverText: '#1e3221',
      scrollbarColor: 'unset',
      scrollbarTrackColor: BOARD_SCROLLBAR_TRACK_TRANSPARENT_HEXA,
    },
  },
  {
    id: 'ruby-red',
    name: 'Ruby Red',
    palette: {
      navbarBg: '#9d3d2b',
      navbarBorder: '#ffffff2e',
      canvasBg: '#b8503a',
      listBg: '#ffffff',
      listHeaderText: '#3a1f1b',
      listMuted: '#715552',
      listMutedStrong: '#553a37',
      listControlHoverBg: '#0000000f',
      listShadow: '0 1px 3px #00000021',
      addListBg: '#ffffff33',
      addListBgHover: '#ffffff4d',
      cardDetailBg: '#faf7f7',
      cardDetailTitleText: '#1a1b1e',
      cardDetailText: '#7a5e5e',
      cardDetailButtonBg: '#f3ecec',
      cardDetailButtonText: '#3c2323',
      cardDetailButtonHoverBg: '#e7dddd',
      cardDetailButtonHoverText: '#3c2323',
      scrollbarColor: 'unset',
      scrollbarTrackColor: BOARD_SCROLLBAR_TRACK_TRANSPARENT_HEXA,
    },
  },
  {
    id: 'royal-purple',
    name: 'Royal Purple',
    palette: {
      navbarBg: '#7b5db5',
      navbarBorder: '#ffffff2e',
      canvasBg: '#987ad0',
      listBg: '#ffffff',
      listHeaderText: '#2a2242',
      listMuted: '#625a79',
      listMutedStrong: '#4a4262',
      listControlHoverBg: '#0000000f',
      listShadow: '0 1px 3px #00000021',
      addListBg: '#ffffff38',
      addListBgHover: '#ffffff4f',
      cardDetailBg: '#f8f7fb',
      cardDetailTitleText: '#1a1b1e',
      cardDetailText: '#676080',
      cardDetailButtonBg: '#efecf7',
      cardDetailButtonText: '#2a2242',
      cardDetailButtonHoverBg: '#e3ddf1',
      cardDetailButtonHoverText: '#2a2242',
      scrollbarColor: 'unset',
      scrollbarTrackColor: BOARD_SCROLLBAR_TRACK_TRANSPARENT_HEXA,
    },
  },
  {
    id: 'hot-pink',
    name: 'Hot Pink',
    palette: {
      navbarBg: '#c04a97',
      navbarBorder: '#ffffff33',
      canvasBg: '#dc65af',
      listBg: '#ffffff',
      listHeaderText: '#3f1f33',
      listMuted: '#7a5c71',
      listMutedStrong: '#604657',
      listControlHoverBg: '#0000000f',
      listShadow: '0 1px 3px #00000021',
      addListBg: '#ffffff3b',
      addListBgHover: '#ffffff54',
      cardDetailBg: '#fbf7fa',
      cardDetailTitleText: '#1a1b1e',
      cardDetailText: '#7b6273',
      cardDetailButtonBg: '#f3ecf1',
      cardDetailButtonText: '#3f1f33',
      cardDetailButtonHoverBg: '#e8dde6',
      cardDetailButtonHoverText: '#3f1f33',
      scrollbarColor: 'unset',
      scrollbarTrackColor: BOARD_SCROLLBAR_TRACK_TRANSPARENT_HEXA,
    },
  },
  {
    id: 'mint-green',
    name: 'Mint Green',
    palette: {
      navbarBg: '#53b972',
      navbarBorder: '#ffffff29',
      canvasBg: '#75cf8f',
      listBg: '#ffffff',
      listHeaderText: '#193226',
      listMuted: '#567666',
      listMutedStrong: '#3f5c4e',
      listControlHoverBg: '#0000000f',
      listShadow: '0 1px 3px #0000001f',
      addListBg: '#ffffff33',
      addListBgHover: '#ffffff4f',
      cardDetailBg: '#f7fbf8',
      cardDetailTitleText: '#1a1b1e',
      cardDetailText: '#5a7568',
      cardDetailButtonBg: '#edf4ef',
      cardDetailButtonText: '#1f3329',
      cardDetailButtonHoverBg: '#dfe9e2',
      cardDetailButtonHoverText: '#1f3329',
      scrollbarColor: 'unset',
      scrollbarTrackColor: BOARD_SCROLLBAR_TRACK_TRANSPARENT_HEXA,
    },
  },
  {
    id: 'teal',
    name: 'Teal',
    palette: {
      navbarBg: '#2f9abc',
      navbarBorder: '#ffffff2e',
      canvasBg: '#46b3d7',
      listBg: '#ffffff',
      listHeaderText: '#17353e',
      listMuted: '#5a7480',
      listMutedStrong: '#435c66',
      listControlHoverBg: '#0000000f',
      listShadow: '0 1px 3px #0000001f',
      addListBg: '#ffffff33',
      addListBgHover: '#ffffff4d',
      cardDetailBg: '#f7fafb',
      cardDetailTitleText: '#1a1b1e',
      cardDetailText: '#5a717a',
      cardDetailButtonBg: '#edf3f5',
      cardDetailButtonText: '#18323a',
      cardDetailButtonHoverBg: '#dee8eb',
      cardDetailButtonHoverText: '#18323a',
      scrollbarColor: 'unset',
      scrollbarTrackColor: BOARD_SCROLLBAR_TRACK_TRANSPARENT_HEXA,
    },
  },
] as const;

/** Swatches for theme editor nav/canvas pickers (navbar then canvas per system theme). */
export const BOARD_THEME_EDITOR_NAV_CANVAS_SWATCHES: readonly string[] = SYSTEM_BOARD_THEME_SEEDS.flatMap(
  (theme) => [`${theme.palette.navbarBg}ff`, `${theme.palette.canvasBg}ff`],
);
