#!/usr/bin/env bash
# Install or patch host nginx so app deploys pick up reverse-proxy changes.
#
# Kanboard sample (deploy/nginx/kanboard.conf): replace the detected/explicit site.
# Installer site (upstream atlantisboard_app): upsert the backup-import location only
# so TLS paths and certbot edits stay put.
#
# Usage:
#   apply-nginx-config-update.sh --src deploy/nginx --site /etc/nginx/sites-available/kanboard
#   apply-nginx-config-update.sh --src deploy/nginx --detect
#   apply-nginx-config-update.sh --site /etc/nginx/sites-available/atlantisboard
#
set -euo pipefail

SRC_DIR=""
SITE_PATH=""
SNIPPET_PATH=""
NGINX_ROOT="/etc/nginx"
DETECT=false
SKIP_NGINX_TEST=false
SKIP_RELOAD=false
DRY_RUN=false

die() {
  printf 'apply-nginx-config-update: %s\n' "$*" >&2
  exit 1
}

log() {
  printf 'apply-nginx-config-update: %s\n' "$*"
}

usage() {
  sed -n '2,14p' "$0" | sed 's/^# \{0,1\}//'
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --src)
      SRC_DIR="$2"
      shift 2
      ;;
    --site)
      SITE_PATH="$2"
      shift 2
      ;;
    --snippet)
      SNIPPET_PATH="$2"
      shift 2
      ;;
    --nginx-root)
      NGINX_ROOT="$2"
      shift 2
      ;;
    --detect)
      DETECT=true
      shift
      ;;
    --skip-nginx-test)
      SKIP_NGINX_TEST=true
      shift
      ;;
    --skip-reload)
      SKIP_RELOAD=true
      shift
      ;;
    --dry-run)
      DRY_RUN=true
      shift
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      die "unknown option: $1"
      ;;
  esac
done

is_installer_site() {
  local path="$1"
  [[ -f "$path" ]] || return 1
  grep -Eq 'upstream[[:space:]]+atlantisboard_app|generated by atlantisboard-setup' "$path"
}

is_kanboard_site() {
  local path="$1"
  [[ -f "$path" ]] || return 1
  grep -Eq 'upstream[[:space:]]+kanboard_app|kanboard-proxy\.conf|server_name[[:space:]]+app\.atlantis\.social' "$path"
}

detect_site() {
  local -a candidates=()
  local f
  for f in \
    "${NGINX_ROOT}/sites-enabled/kanboard" \
    "${NGINX_ROOT}/sites-enabled/kanboard.conf" \
    "${NGINX_ROOT}/sites-available/kanboard" \
    "${NGINX_ROOT}/sites-available/kanboard.conf" \
    "${NGINX_ROOT}/conf.d/kanboard.conf"; do
    if [[ -f "$f" || -L "$f" ]]; then
      printf '%s\n' "$f"
      return 0
    fi
  done

  if [[ -d "${NGINX_ROOT}/sites-enabled" ]]; then
    while IFS= read -r f; do
      candidates+=("$f")
    done < <(find "${NGINX_ROOT}/sites-enabled" -maxdepth 1 \( -type f -o -type l \) 2>/dev/null | sort)
  fi
  if [[ -d "${NGINX_ROOT}/sites-available" ]]; then
    while IFS= read -r f; do
      candidates+=("$f")
    done < <(find "${NGINX_ROOT}/sites-available" -maxdepth 1 \( -type f -o -type l \) 2>/dev/null | sort)
  fi
  if [[ -d "${NGINX_ROOT}/conf.d" ]]; then
    while IFS= read -r f; do
      candidates+=("$f")
    done < <(find "${NGINX_ROOT}/conf.d" -maxdepth 1 -type f -name '*.conf' 2>/dev/null | sort)
  fi

  for f in "${candidates[@]}"; do
    if is_kanboard_site "$f"; then
      printf '%s\n' "$f"
      return 0
    fi
  done
  for f in "${candidates[@]}"; do
    if is_installer_site "$f"; then
      printf '%s\n' "$f"
      return 0
    fi
  done
  return 1
}

backup_import_block() {
  local upstream="$1"
  cat <<EOF
    # Disaster-recovery backup ZIP import — stream multi-GB bodies, do not buffer.
    location ^~ /api/v1/admin/backup/import {
        client_max_body_size 100g;
        proxy_request_buffering off;
        proxy_buffering off;
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;

        proxy_pass http://${upstream};
        proxy_http_version 1.1;
        proxy_set_header Host              \$host;
        proxy_set_header X-Real-IP         \$remote_addr;
        proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Connection        "";
    }
EOF
}

upsert_backup_import() {
  local site="$1"
  local upstream="$2"
  local block_file
  block_file="$(mktemp)"
  backup_import_block "$upstream" >"$block_file"
  python3 - "$site" "$block_file" <<'PY'
from pathlib import Path
import re
import sys

site = Path(sys.argv[1])
block = Path(sys.argv[2]).read_text()
if not block.endswith("\n"):
    block += "\n"
text = site.read_text()
pat = re.compile(
    r"^[ \t]*# Disaster-recovery backup ZIP import[^\n]*\n"
    r"^[ \t]*location \^~ /api/v1/admin/backup/import\s*\{.*?\n[ \t]*\}\n"
    r"|"
    r"^[ \t]*location \^~ /api/v1/admin/backup/import\s*\{.*?\n[ \t]*\}\n",
    re.M | re.S,
)
if pat.search(text):
    text = pat.sub(block, text, count=1)
else:
    match = re.search(r"^[ \t]*location /\s*\{", text, re.M)
    if match is None:
        sys.exit("apply-nginx-config-update: no location / block to insert before")
    text = text[: match.start()] + block + "\n" + text[match.start() :]
site.write_text(text)
PY
  rm -f "$block_file"
}

nginx_bin() {
  if command -v nginx >/dev/null 2>&1; then
    command -v nginx
    return 0
  fi
  if [[ -x /usr/sbin/nginx ]]; then
    printf '%s\n' /usr/sbin/nginx
    return 0
  fi
  return 1
}

install_file() {
  local src="$1"
  local dest="$2"
  local dest_dir
  dest_dir="$(dirname "$dest")"
  if [[ "$DRY_RUN" == true ]]; then
    log "[dry-run] install $src -> $dest"
    return 0
  fi
  mkdir -p "$dest_dir"
  if [[ -e "$dest" || -L "$dest" ]]; then
    cp -a "$dest" "${dest}.bak.atlantisboard-deploy"
  fi
  cp -a "$src" "$dest"
}

restore_backup() {
  local dest="$1"
  local bak="${dest}.bak.atlantisboard-deploy"
  if [[ -e "$bak" || -L "$bak" ]]; then
    cp -a "$bak" "$dest"
  fi
}

if [[ "$DETECT" == true && -z "$SITE_PATH" ]]; then
  SITE_PATH="$(detect_site || true)"
  if [[ -z "$SITE_PATH" ]]; then
    log "no kanboard/atlantisboard nginx site under ${NGINX_ROOT} — skipping"
    exit 0
  fi
  log "detected site ${SITE_PATH}"
fi

[[ -n "$SITE_PATH" ]] || die "need --site or --detect"
if command -v readlink >/dev/null 2>&1; then
  SITE_PATH="$(readlink -f "$SITE_PATH" || printf '%s' "$SITE_PATH")"
fi

if [[ -e "$SITE_PATH" || -L "$SITE_PATH" ]] && is_installer_site "$SITE_PATH"; then
  log "upserting backup-import location in installer site ${SITE_PATH}"
  if [[ "$DRY_RUN" == true ]]; then
    log "[dry-run] upsert location ^~ /api/v1/admin/backup/import"
    exit 0
  fi
  command -v python3 >/dev/null 2>&1 || die "python3 required to patch installer nginx site"
  cp -a "$SITE_PATH" "${SITE_PATH}.bak.atlantisboard-deploy"
  upsert_backup_import "$SITE_PATH" "atlantisboard_app"
else
  [[ -n "$SRC_DIR" ]] || die "kanboard site replace needs --src (directory with kanboard.conf)"
  local_sample="${SRC_DIR}/kanboard.conf"
  [[ -f "$local_sample" ]] || die "missing ${local_sample}"
  log "installing ${local_sample} -> ${SITE_PATH}"
  install_file "$local_sample" "$SITE_PATH"

  local_snippet="${SRC_DIR}/kanboard-proxy.conf"
  if [[ -f "$local_snippet" ]]; then
    if [[ -z "$SNIPPET_PATH" ]]; then
      SNIPPET_PATH="${NGINX_ROOT}/snippets/kanboard-proxy.conf"
    fi
    log "installing ${local_snippet} -> ${SNIPPET_PATH}"
    install_file "$local_snippet" "$SNIPPET_PATH"
  fi
fi

if [[ "$SKIP_NGINX_TEST" != true ]]; then
  bin="$(nginx_bin)" || die "nginx binary not found (use --skip-nginx-test)"
  if [[ "$DRY_RUN" == true ]]; then
    log "[dry-run] $bin -t"
  elif ! "$bin" -t; then
    log "nginx -t failed — restoring previous site"
    restore_backup "$SITE_PATH"
    if [[ -n "$SNIPPET_PATH" ]]; then
      restore_backup "$SNIPPET_PATH"
    fi
    die "nginx -t failed; previous config restored"
  fi
fi

if [[ "$SKIP_RELOAD" != true ]]; then
  if [[ "$DRY_RUN" == true ]]; then
    log "[dry-run] nginx reload"
  elif command -v systemctl >/dev/null 2>&1 && systemctl is-active --quiet nginx 2>/dev/null; then
    systemctl reload nginx
  else
    bin="$(nginx_bin)" || die "nginx binary not found (use --skip-reload)"
    "$bin" -s reload
  fi
fi

log "ok"
