// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Handle clock skew by allowing some tolerance in session validation
    // This helps when system clocks are slightly out of sync
    detectSessionInUrl: true,
    flowType: 'pkce',
  },
  global: {
    // Add headers that might help with clock skew issues
    headers: {
      'X-Client-Info': 'atlantisboard-web',
    },
  },
});